
  # LoginResult LoginResult 接口字段
  fragment LoginResultsFields on LoginResult {
    
  }

  # 列表
  query LoginResults ($currentPage: Int = 1, $perPage: Int = 10, $sort: [LoginResultSortType!], $search: String, $filter: LoginResultFilterType, $rand: Boolean = false) {
    loginResults(current_page: $currentPage, per_page: $perPage, sort: $sort, q: $search, filter: $filter, rand: $rand) {
      data {
        
      }
      current_page
      per_page
      total
      total_page
    }
  }

  # 详情
  query LoginResultDetail ($id: ID, $search: String, $filter: LoginResultFilterType) {
    loginResult(id: $id, q: $search, filter: $filter) {
      
    }
  }

  # 新增
  mutation createLoginResult ($data: CreateLoginResultInput!) {
    createLoginResult(input: $data) {
      id
    }
  }

  # 修改
  mutation updateLoginResult ($id: ID!, $data: UpdateLoginResultInput!) {
    updateLoginResult(id: $id, input: $data) {
      id
    }
  }

  # 删除
  mutation deleteLoginResults ($id: [ID!]!) {
    deleteLoginResults(id: $id)
  }

  # 恢复删除
  mutation recoveryLoginResults ($id: [ID!]!) {
    recoveryLoginResults(id: $id)
  }

  # LoginCompanyOption LoginCompanyOption 接口字段
  fragment LoginCompanyOptionsFields on LoginCompanyOption {
    
  }

  # 列表
  query LoginCompanyOptions ($currentPage: Int = 1, $perPage: Int = 10, $sort: [LoginCompanyOptionSortType!], $search: String, $filter: LoginCompanyOptionFilterType, $rand: Boolean = false) {
    loginCompanyOptions(current_page: $currentPage, per_page: $perPage, sort: $sort, q: $search, filter: $filter, rand: $rand) {
      data {
        
      }
      current_page
      per_page
      total
      total_page
    }
  }

  # 详情
  query LoginCompanyOptionDetail ($id: ID, $search: String, $filter: LoginCompanyOptionFilterType) {
    loginCompanyOption(id: $id, q: $search, filter: $filter) {
      
    }
  }

  # 新增
  mutation createLoginCompanyOption ($data: CreateLoginCompanyOptionInput!) {
    createLoginCompanyOption(input: $data) {
      id
    }
  }

  # 修改
  mutation updateLoginCompanyOption ($id: ID!, $data: UpdateLoginCompanyOptionInput!) {
    updateLoginCompanyOption(id: $id, input: $data) {
      id
    }
  }

  # 删除
  mutation deleteLoginCompanyOptions ($id: [ID!]!) {
    deleteLoginCompanyOptions(id: $id)
  }

  # 恢复删除
  mutation recoveryLoginCompanyOptions ($id: [ID!]!) {
    recoveryLoginCompanyOptions(id: $id)
  }

  # 用户管理 User 接口字段
  fragment UsersFields on User {
    id
    phone
    password
    email
    nickname
    age
    lastName
    isDelete
    weight
    state
    deletedBy
    updatedBy
    createdBy
    deletedAt
    updatedAt
    createdAt
    
  }

  # 列表
  query Users ($currentPage: Int = 1, $perPage: Int = 10, $sort: [UserSortType!], $search: String, $filter: UserFilterType, $rand: Boolean = false) {
    users(current_page: $currentPage, per_page: $perPage, sort: $sort, q: $search, filter: $filter, rand: $rand) {
      data {
        id
        phone
        password
        email
        nickname
        age
        lastName
        isDelete
        weight
        state
        deletedBy
        updatedBy
        createdBy
        deletedAt
        updatedAt
        createdAt
        tasks {
          ...TasksFields
        }
        
      }
      current_page
      per_page
      total
      total_page
    }
  }

  # 详情
  query UserDetail ($id: ID, $search: String, $filter: UserFilterType) {
    user(id: $id, q: $search, filter: $filter) {
      id
      phone
      password
      email
      nickname
      age
      lastName
      isDelete
      weight
      state
      deletedBy
      updatedBy
      createdBy
      deletedAt
      updatedAt
      createdAt
      tasks {
        ...TasksFields
      }
      
    }
  }

  # 新增
  mutation createUser ($data: CreateUserInput!) {
    createUser(input: $data) {
      id
    }
  }

  # 修改
  mutation updateUser ($id: ID!, $data: UpdateUserInput!) {
    updateUser(id: $id, input: $data) {
      id
    }
  }

  # 删除
  mutation deleteUsers ($id: [ID!]!) {
    deleteUsers(id: $id)
  }

  # 恢复删除
  mutation recoveryUsers ($id: [ID!]!) {
    recoveryUsers(id: $id)
  }

  # 任务管理 Task 接口字段
  fragment TasksFields on Task {
    id
    title
    completed
    dueDate
    userId
    isDelete
    weight
    state
    deletedBy
    updatedBy
    createdBy
    deletedAt
    updatedAt
    createdAt
    
  }

  # 列表
  query Tasks ($currentPage: Int = 1, $perPage: Int = 10, $sort: [TaskSortType!], $search: String, $filter: TaskFilterType, $rand: Boolean = false) {
    tasks(current_page: $currentPage, per_page: $perPage, sort: $sort, q: $search, filter: $filter, rand: $rand) {
      data {
        id
        title
        completed
        dueDate
        userId
        isDelete
        weight
        state
        deletedBy
        updatedBy
        createdBy
        deletedAt
        updatedAt
        createdAt
        user {
          ...UsersFields
        }
        
      }
      current_page
      per_page
      total
      total_page
    }
  }

  # 详情
  query TaskDetail ($id: ID, $search: String, $filter: TaskFilterType) {
    task(id: $id, q: $search, filter: $filter) {
      id
      title
      completed
      dueDate
      userId
      isDelete
      weight
      state
      deletedBy
      updatedBy
      createdBy
      deletedAt
      updatedAt
      createdAt
      user {
        ...UsersFields
      }
      
    }
  }

  # 新增
  mutation createTask ($data: CreateTaskInput!) {
    createTask(input: $data) {
      id
    }
  }

  # 修改
  mutation updateTask ($id: ID!, $data: UpdateTaskInput!) {
    updateTask(id: $id, input: $data) {
      id
    }
  }

  # 删除
  mutation deleteTasks ($id: [ID!]!) {
    deleteTasks(id: $id)
  }

  # 恢复删除
  mutation recoveryTasks ($id: [ID!]!) {
    recoveryTasks(id: $id)
  }


  
  # login 接口
  query login($input: loginParams!) {
    login(input: $input) {
      ...LoginResultsFields
    }
  }
  
  # webSocket 接口
  subscription webSocket {
    webSocket
  }
